version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrantdata:/qdrant/storage

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env.local
    ports:
      - "5000:5000"
    command: ["node", "dist/index.js"]
    depends_on:
      - redis
      - qdrant
      - postgres

  worker:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env.local
    command: ["node", "dist/workers/pdfProcessorWorker.js"]
    depends_on:
      - redis
      - qdrant
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  pgdata:
  qdrantdata:
