version: "3.8"

services:
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

  app:
    build: .
    container_name: orion-server
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - qdrant
    command: ["node", "dist/index.js"]

  worker:
    build: .
    container_name: orion-worker
    env_file: .env
    depends_on:
      - redis
      - qdrant
    command: ["node", "dist/workers/pdfProcessorWorker.js"]
